services:
  claude-code-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVER__HOST=0.0.0.0
      - SERVER__PORT=8000
      - LOGGING__LEVEL=INFO
      - LOGGING__FORMAT=json
      - LOGGING__ENABLE_PLUGIN_LOGGING=true
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    # env_file:
    #   - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$SERVER__PORT/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
