name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  boundaries:
    name: Import Boundaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-path: |
            uv.lock

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run boundary checks
        run: make check-boundaries

  lint:
    name: Lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-path: |
            uv.lock
      - name: Install deps
        run: uv sync --all-extras --dev
      - name: Ruff check
        run: uv run ruff check .

  typecheck:
    name: Typecheck (mypy)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-path: |
            uv.lock
      - name: Install deps
        run: uv sync --all-extras --dev
      - name: mypy
        run: uv run mypy .

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-path: |
            uv.lock
      - name: Install deps
        run: uv sync --all-extras --dev
      - name: Run unit tests (no network)
        run: uv run pytest tests/unit -m "not real_api" --durations=10 -q
